import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$400,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    description: "The Nike Air Monarch IV is built for comfort and style with its cushioning system and supportive structure, ideal for casual or athletic wear.",
    stock: 35,
    sizeOptions: ["7", "8", "9", "10", "11", "12"],
    material: "Leather",
    shipping: "Free standard shipping on orders over $50.",
    reviews: [
      { user: "John Doe", rating: 5, comment: "Great fit and very comfortable for long walks!" },
      { user: "Sarah Lee", rating: 4, comment: "Stylish shoes but a bit tight in the toe area." },
    ],
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    rating: "3",
    prevPrice: "$300,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    description: "Nike Air Vapormax Plus combines futuristic aesthetics and maximum comfort, designed with advanced air cushioning for a smooth ride.",
    stock: 50,
    sizeOptions: ["8", "9", "10", "11"],
    material: "Synthetic Mesh",
    shipping: "Standard shipping costs $5, expedited available.",
    reviews: [
      { user: "Alice Johnson", rating: 3, comment: "Nice look but not as comfortable as expected." },
      { user: "Mike Brown", rating: 3, comment: "Great for style, but lacking in arch support." },
    ],
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$100,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    description: "The Nike Waffle One features the classic Waffle outsole and lightweight, breathable design that keeps your feet comfortable all day.",
    stock: 20,
    sizeOptions: ["6", "7", "8", "9", "10"],
    material: "Canvas, Rubber",
    shipping: "Free shipping and returns on all orders.",
    reviews: [
      { user: "Charlie White", rating: 5, comment: "Perfect fit and super comfortable!" },
      { user: "Jessica Green", rating: 4, comment: "Good value for the price, but the green color is a bit brighter than expected." },
    ],
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    rating: "5",
    prevPrice: "$600,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
    description: "Lightweight and durable, the Nike Running Shoe is perfect for long-distance runners and those looking for a responsive cushioning experience.",
    stock: 12,
    sizeOptions: ["7", "8", "9", "10", "11"],
    material: "Mesh, Synthetic",
    shipping: "Free express shipping available for limited time.",
    reviews: [
      { user: "David Wright", rating: 5, comment: "Best running shoes I've ever owned. Very light and fast." },
      { user: "Emma Thomas", rating: 5, comment: "Incredible comfort, I can run for hours without discomfort!" },
    ],
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$650,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
    description: "Elegant and comfortable, these slip-on pumps offer a sleek design perfect for both formal and casual wear.",
    stock: 22,
    sizeOptions: ["5", "6", "7", "8", "9"],
    material: "Suede",
    shipping: "Free returns within 30 days.",
    reviews: [
      { user: "Maggie Scott", rating: 4, comment: "Great shoes for work, very comfortable and stylish." },
      { user: "Rachel Lee", rating: 4, comment: "The color is beautiful, though the fit is slightly narrow." },
    ],
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    rating: "3",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    description: "The Knit Ballet Flat is a simple yet chic option, with a flexible knit design that adapts to the shape of your foot.",
    stock: 15,
    sizeOptions: ["5", "6", "7", "8"],
    material: "Knit",
    shipping: "Free shipping on orders over $100.",
    reviews: [
      { user: "Sophia Kim", rating: 3, comment: "Nice for casual wear, but the sole feels a bit thin." },
      { user: "Olivia Carter", rating: 3, comment: "A good buy for the price, though not the most durable." },
    ],
  },
  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    rating: "2",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
    description: "Simple loafer flats designed for comfort and versatility, perfect for everyday wear.",
    stock: 25,
    sizeOptions: ["6", "7", "8"],
    material: "Synthetic Leather",
    shipping: "Standard shipping free on orders above $50.",
    reviews: [
      { user: "Lucas Brown", rating: 2, comment: "Not bad but they didn't last long." },
      { user: "Emma Green", rating: 2, comment: "Slightly uncomfortable after wearing for hours." },
    ],
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    rating: "2",
    prevPrice: "$1400,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    description: "The Nike Zoom Freak is designed for maximum performance with a responsive cushioning system and an eye-catching design.",
    stock: 30,
    sizeOptions: ["7", "8", "9", "10", "11"],
    material: "Mesh, Rubber",
    shipping: "Expedited shipping available for $10.",
    reviews: [
      { user: "John Smith", rating: 2, comment: "Not as good as expected. Cushioning could be better." },
      { user: "Kylie Roberts", rating: 2, comment: "Too bulky for my liking, but stylish." },
    ],
  },
  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    rating: "1",
    prevPrice: "$1400,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    description: "Nike Men's Sneaker offers a sleek look with a solid construction, designed to meet both style and performance.",
    stock: 18,
    sizeOptions: ["8", "9", "10", "11"],
    material: "Synthetic, Mesh",
    shipping: "Free shipping on orders over $100.",
    reviews: [
      { user: "Michael Gray", rating: 1, comment: "Terrible fit and uncomfortable after wearing for an hour." },
      { user: "David Johnson", rating: 1, comment: "The quality feels cheap and uncomfortable." },
    ],
  },
  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$1140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
    description: "PUMA Black-Oce sneakers blend sporty elegance with maximum comfort for the modern athlete.",
    stock: 50,
    sizeOptions: ["7", "8", "9", "10", "11"],
    material: "Mesh, Rubber",
    shipping: "Standard shipping available at $5.",
    reviews: [
      { user: "Liam Scott", rating: 4, comment: "Very comfortable and stylish. I wear them for running." },
      { user: "Ella Parker", rating: 4, comment: "Good fit, but a little stiff initially." },
    ],
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    rating: "1",
    prevPrice: "$240,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
    description: "The Pacer Future Sneaker offers a futuristic design with a comfortable and supportive fit, designed for both style and performance.",
    stock: 40,
    sizeOptions: ["7", "8", "9", "10"],
    material: "Mesh, Synthetic",
    shipping: "Free standard shipping on orders over $50.",
    reviews: [
      { user: "Jake Miller", rating: 1, comment: "Uncomfortable and poor quality." },
      { user: "Anna Davis", rating: 1, comment: "Not happy with the fit or feel." },
    ],
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    rating: "5",
    prevPrice: "$1000,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    description: "Unisex-Adult Super sneakers blend classic design with modern materials, perfect for everyday wear or casual outings.",
    stock: 60,
    sizeOptions: ["7", "8", "9", "10", "11"],
    material: "Synthetic, Rubber",
    shipping: "Free shipping on orders over $100.",
    reviews: [
      { user: "Oliver Martinez", rating: 5, comment: "Incredible comfort and style!" },
      { user: "Sophia Roberts", rating: 5, comment: "Perfect fit and super breathable." },
    ],
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$250,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
    description: "The Roma Basic Sneaker is a timeless classic, providing both comfort and versatile style for any casual outfit.",
    stock: 30,
    sizeOptions: ["6", "7", "8", "9", "10"],
    material: "Leather, Rubber",
    shipping: "Free shipping and returns on all orders.",
    reviews: [
      { user: "Emily Clark", rating: 4, comment: "Great shoes for casual wear!" },
      { user: "Liam Young", rating: 4, comment: "Comfortable, but a bit tight in the toe area." },
    ],
  },
  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    rating: "2",
    prevPrice: "$600,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    description: "Pacer Future Doubleknit sneakers offer a modern design with advanced comfort features, suitable for both athletic and casual wear.",
    stock: 50,
    sizeOptions: ["7", "8", "9", "10"],
    material: "Double-knit fabric, Rubber",
    shipping: "Standard shipping costs $5, expedited available.",
    reviews: [
      { user: "Mason Lewis", rating: 2, comment: "Not what I expected, too bulky and uncomfortable." },
      { user: "Isabella Martin", rating: 2, comment: "The fit is off, but the design is nice." },
    ],
  },
  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    rating: "1",
    prevPrice: "$300,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
    description: "The Fusion Evo Golf Shoe provides traction and comfort on the course, designed for both performance and style.",
    stock: 10,
    sizeOptions: ["8", "9", "10", "11"],
    material: "Leather, Synthetic",
    shipping: "Free express shipping available for limited time.",
    reviews: [
      { user: "James Wilson", rating: 1, comment: "Terrible quality, didn't last." },
      { user: "Chloe Green", rating: 1, comment: "Uncomfortable and not durable." },
    ],
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    rating: "3",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
    description: "The Rainbow Chex Skate flat shoes offer a stylish look with superior comfort, perfect for everyday wear.",
    stock: 35,
    sizeOptions: ["6", "7", "8", "9"],
    material: "Canvas",
    shipping: "Free returns within 30 days.",
    reviews: [
      { user: "Jack Thomas", rating: 3, comment: "Nice but the fit is a bit off." },
      { user: "Hannah Wilson", rating: 3, comment: "Cute shoes, but not as comfortable as expected." },
    ],
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
    description: "Low-Top Trainers combine classic design with modern comfort, perfect for casual outings.",
    stock: 45,
    sizeOptions: ["6", "7", "8", "9", "10"],
    material: "Mesh, Rubber",
    shipping: "Free shipping on orders over $50.",
    reviews: [
      { user: "Benjamin Harris", rating: 4, comment: "Great trainers for the price, very comfortable." },
      { user: "Megan Lee", rating: 4, comment: "Very stylish, though the fit is a bit tight." },
    ],
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    rating: "5",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
    description: "Vans Unisex Low-Top sneakers are designed for all-day comfort with their soft padding and durable sole.",
    stock: 30,
    sizeOptions: ["7", "8", "9", "10"],
    material: "Canvas",
    shipping: "Free shipping on orders over $100.",
    reviews: [
      { user: "Lucas Wilson", rating: 5, comment: "Perfect fit and comfortable for long hours!" },
      { user: "Olivia Smith", rating: 5, comment: "Love the color and the feel. Definitely recommend!" },
    ],
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    rating: "2",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
    description: "Classic Bandana Sneakers combine a trendy bandana print with Nike's signature comfort and performance.",
    stock: 25,
    sizeOptions: ["7", "8", "9", "10"],
    material: "Canvas, Rubber",
    shipping: "Standard shipping free on orders above $50.",
    reviews: [
      { user: "Sophia Harris", rating: 2, comment: "The fit is awkward and uncomfortable after a while." },
      { user: "Ethan Adams", rating: 2, comment: "Not great quality for the price." },
    ],
  },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    rating: "1",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
    description: "Chunky High Heel sandals are designed for maximum height and comfort, but the fit can be a bit off.",
    stock: 15,
    sizeOptions: ["5", "6", "7", "8"],
    material: "Synthetic Leather",
    shipping: "Free returns within 30 days.",
    reviews: [
      { user: "Ava Brown", rating: 1, comment: "Too uncomfortable for long wear." },
      { user: "Mia Miller", rating: 1, comment: "Not what I expected, not very stable." },
    ],
  },
  {
    id: 21,
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    rating: "3",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "black",
    category: "heels",
    description: "The Slip On Stiletto High Heel offers a chic, slip-on design with a tall stiletto heel for a fashionable look.",
    stock: 20,
    sizeOptions: ["6", "7", "8", "9"],
    material: "Leather",
    shipping: "Expedited shipping available for $10.",
    reviews: [
      { user: "Ella Jones", rating: 3, comment: "Stylish, but not the most comfortable." },
      { user: "Amelia King", rating: 3, comment: "Nice for short periods, but hard to wear all day." },
    ],
  },
  {
    id: 22,
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    rating: "3",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
    description: "DREAM PAIRS Court Shoes provide a sophisticated court style with a comfortable and supportive fit, designed for fashion lovers.",
    stock: 30,
    sizeOptions: ["6", "7", "8", "9"],
    material: "Satin, Synthetic",
    shipping: "Standard shipping free with orders above $50.",
    reviews: [
      { user: "Isla Martin", rating: 3, comment: "Pretty, but can be a bit tight around the toes." },
      { user: "Charlotte Taylor", rating: 3, comment: "Good quality, but not the most comfortable for long wear." },
    ],
  },
  {
    id: 23,
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    rating: "1",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    description: "The Nike Air Vapormax Plus features a futuristic design with advanced air-cushioning for a smooth, comfortable ride.",
    stock: 10,
    sizeOptions: ["8", "9", "10"],
    material: "Synthetic, Rubber",
    shipping: "Free shipping for all orders.",
    reviews: [
      { user: "Noah Scott", rating: 1, comment: "Poor quality, broke after one month." },
      { user: "Amelia White", rating: 1, comment: "Not worth the price. Uncomfortable fit." },
    ],
  },
  {
    id: 24,
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    rating: "4",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "heels",
    description: "Low Mid Block Heels provide a stylish yet comfortable block heel design that offers support and elegance for any occasion.",
    stock: 25,
    sizeOptions: ["7", "8", "9"],
    material: "Leather, Synthetic",
    shipping: "Free shipping on orders above $100.",
    reviews: [
      { user: "Lily Davis", rating: 4, comment: "Comfortable and stylish, a perfect blend." },
      { user: "Jack Lee", rating: 4, comment: "Solid heels, comfortable for walking." },
    ],
  },
  {
    id: 25,
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    rating: "5",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    description: "Chunky High Heel sandals are bold and fashionable, designed for comfort with a solid platform for support.",
    stock: 20,
    sizeOptions: ["6", "7", "8", "9"],
    material: "Suede, Synthetic",
    shipping: "Free returns available.",
    reviews: [
      { user: "Harper Allen", rating: 5, comment: "In love with these heels! Super comfortable." },
      { user: "Grace Harris", rating: 5, comment: "Love the chunky heel, very comfortable to walk in." },
    ],
  },
  {
    id: 26,
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    rating: "3",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
    description: "Amore Fashion Stilettos combine elegance and comfort with a sleek design perfect for formal occasions.",
    stock: 25,
    sizeOptions: ["5", "6", "7", "8"],
    material: "Leather",
    shipping: "Standard shipping free for orders over $50.",
    reviews: [
      { user: "Ava Davis", rating: 3, comment: "Good heels but could be more comfortable." },
      { user: "Charlotte Brown", rating: 3, comment: "Stylish, but the heel height could be lower." },
    ],
  },
  {
    id: 27,
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    rating: "5",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    description: "Bridal Sandals Glitter are designed for special occasions, offering elegance with a touch of sparkle.",
    stock: 40,
    sizeOptions: ["5", "6", "7", "8"],
    material: "Satin, Glitter",
    shipping: "Free shipping on orders above $100.",
    reviews: [
      { user: "Lily Martin", rating: 5, comment: "Perfect for my wedding day!" },
      { user: "Sophia Lee", rating: 5, comment: "Beautiful sandals, very comfortable!" },
    ],
  },
  {
    id: 28,
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    rating: "2",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    description: "Wedding Prom Bridal flats are perfect for your special day, offering comfort and elegance in one package.",
    stock: 30,
    sizeOptions: ["5", "6", "7", "8"],
    material: "Leather, Satin",
    shipping: "Free returns on all orders.",
    reviews: [
      { user: "Isabella Walker", rating: 2, comment: "The fit was off, not as comfortable as I expected." },
      { user: "Charlotte King", rating: 2, comment: "Not the best fit, I had to return them." },
    ],
  }
];

export default data;
